In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr.shape)
type(arr)

[1 2 3 4 5]
(5,)


numpy.ndarray

In [2]:
arr.reshape((1,4))

ValueError: cannot reshape array of size 5 into shape (1,4)

In [13]:
arr_2d=arr.reshape((1,5))
print(arr_2d) ## converted to 2D array
print(arr_2d.shape)

[[1 2 3 4 5]]
(1, 5)


In [ ]:
arr_2d=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr_2d)
print(arr_2d.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [ ]:
#
arr=np.arange(0,10,1)
print(arr)
arr=np.arange(0,10,2)
print(arr)
print(arr.shape)
print(arr.reshape(5,1))
print(arr.reshape(5,1).shape)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
(5,)
[[0]
 [2]
 [4]
 [6]
 [8]]
(5, 1)


In [ ]:
arr=np.ones((3,4))
print(arr)
print(arr.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


In [ ]:
## Indentity Matrix
arr=np.eye(3)
print(arr)
print(arr.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [ ]:
#Attributes of Numpy
arr = np. array([[1, 2, 3], [4, 5, 6]])
print ("Array: \n", arr)
print ("Shape:", arr.shape)# Output: (2, 3)
print("Number of dimensions:", arr.ndim)# Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int32 (may vary based on platfor
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based

[[1 2 3]
 [4 5 6]]
(2, 3)
Array: 
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [ ]:
### Numpy Vectorized Operations
arr1=np.array ([1,2,3,4,5])
arr2=np.array ([10,20,30,40,50])
### Element Wise addition
print("Addition:", arr1+arr2)
## Element Wise Substraction
print ("Substraction:", arr1-arr2)
# Element-wise multiplication
print("Multiplication:", arr1 * arr2)
# Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [ ]:
## Universal Function
arr=np.array ([2,3,4,5,6])
## square root
print(np.sqrt(arr))
## Exponential
print(np.exp(arr))
## Sine
print(np.sin(arr))
## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [24]:
### Array Slicing and Indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("arr = ",arr)
print("arr[0] = ",arr[0])
#get a specific element [r,c]
print("arr[0][0] = ",arr[0][0])
print("arr[1][2] = ",arr[1][2])
# Get a specific row
print("arr[1:] = ",arr[1:])
# Get a specific column
print("arr[:,1] = ",arr[:,1])

print("arr[1:,2:] = ",arr[1:,2:])
print("arr[0:2] = ",arr[0:2])
print("arr[0:2,2:] = ",arr[0:2,2:])

#[startindex:endindex:stepsize]
print("arr[0,1:-1:2] = ",arr[0,1:-1:2])

arr =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
arr[0] =  [1 2 3 4]
arr[0][0] =  1
arr[1][2] =  7
arr[1:] =  [[ 5  6  7  8]
 [ 9 10 11 12]]
arr[:,1] =  [ 2  6 10]
arr[1:,2:] =  [[ 7  8]
 [11 12]]
arr[0:2] =  [[1 2 3 4]
 [5 6 7 8]]
arr[0:2,2:] =  [[3 4]
 [7 8]]
arr[0,1:-1:2] =  [2]


In [ ]:
### Modify Array elements
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
arr[0,0]=100
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [ ]:
### Statistical Concepts --Normalization
### to have a mean of 0 and a standard deviation of 1.
data=np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np. mean (data)
print("mean = " , mean)
std_dev = np. std(data)
print("std_dev = ",std_dev)
# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

mean =  3.0
std_dev =  1.4142135623730951
Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 101])
# Mean
mean = np. mean (data)
print ("Mean:", mean)
# Median
median = np.median(data)
print ("Median:", median)
# Standard deviation
std_dev = np.std(data)
print ("Standard Deviation:", std_dev)
# Variance
variance = np.var(data)
print("variance : ",variance)

Mean: 14.6
Median: 5.5
Standard Deviation: 28.903978964841503
variance :  835.4400000000002


In [ ]:
## Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
print(data)
print(data>5)
data=data[data>5]
print(data)
data = data[(data>7)&(data<10)]
print(data)

[ 1  2  3  4  5  6  7  8  9 10]
[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[8 9]


In [16]:
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a.ndim)
print(b.ndim)
print(a.dtype)
print(b.dtype)
print(a.size)
print(b.size)
print(a.itemsize)
print(b.itemsize)


1
2
int64
int64
5
10
8
8


### Intializing Diffrent types of Array

In [34]:
zeroArray=np.zeros((5,5))
print(zeroArray)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [36]:
onesArray=np.ones((5,5))
print(onesArray)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [40]:
otherArray=np.full((5,5),2)
print(otherArray)

[[2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]
 [2 2 2 2 2]]


In [42]:
fullLikeArray=np.full_like(a,4)
fullLikeArray2=np.full_like(otherArray,4)
print(a.shape)
print(fullLikeArray)
print(fullLikeArray.shape)
print(fullLikeArray2)
print(fullLikeArray2.shape)

(5,)
[4 4 4 4 4]
(5,)
[[4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]
 [4 4 4 4 4]]
(5, 5)


In [47]:
randomDecimalArray=np.random.rand(4,2)
print(randomDecimalArray)
randomDecimalArray2=np.random.random_sample(a.shape)
print(randomDecimalArray)
print(a.shape)
print(randomDecimalArray.shape)

[[0.31338476 0.45771021]
 [0.61881722 0.85271688]
 [0.71958126 0.66491051]
 [0.80583355 0.4682786 ]]
[[0.31338476 0.45771021]
 [0.61881722 0.85271688]
 [0.71958126 0.66491051]
 [0.80583355 0.4682786 ]]
(5,)
(4, 2)


In [49]:
randomIntArray=np.random.randint(7,size=(3,3))
print(randomIntArray)
randomIntArray2=np.random.randint(1,7,size=(3,3))
print(randomIntArray2)

[[4 6 5]
 [3 3 6]
 [4 4 3]]
[[6 5 5]
 [3 1 2]
 [1 1 5]]


In [50]:
identityMatrix=np.identity(5)
print(identityMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [51]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [68]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4,1:4]=z
print(output)
# print(output[1:4,1:4])

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Mathematics

In [6]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print("a    =   ",a)
print("a+2  =   ",a+2)
print("a-2  =   ",a-2)
print("a*2  =   ",a*2)
print("a**2 =   ",a**2)
print("a/2  =   ",a/2)
print("a//2 =   ",a//2)
print("a%2  =   ",a%2)
print("np.cos(a) =   ",np.cos(a))

a    =    [ 1  2  3  4  5  6  7  8  9 10]
a+2  =    [ 3  4  5  6  7  8  9 10 11 12]
a-2  =    [-1  0  1  2  3  4  5  6  7  8]
a*2  =    [ 2  4  6  8 10 12 14 16 18 20]
a**2 =    [  1   4   9  16  25  36  49  64  81 100]
a/2  =    [0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
a//2 =    [0 1 1 2 2 3 3 4 4 5]
a%2  =    [1 0 1 0 1 0 1 0 1 0]


### Linear Algebrs

In [9]:
a=np.ones((2,3))
print("a   =   \n",a)
b=np.full((3,2),2)
print("b   =   \n",b)
print("a*b =   \n",np.matmul(a,b))

a   =   
 [[1. 1. 1.]
 [1. 1. 1.]]
b   =   
 [[2 2]
 [2 2]
 [2 2]]
a*b =   
 [[6. 6.]
 [6. 6.]]


In [10]:
### Determinant of a matrix
c=np.identity(3)
print(c) # Output: [[1. 0. 0.], [0. 1. 0.], [0. 0. 1.]] 
#linalg is a sub-module of NumPy that provides functions to perform linear algebra operations.
print("determinant of the Matrix",np.linalg.det(c)) # Output: 1.0 


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


### Statistics

In [12]:
stats=np.array([[1,2,3],[4,5,6]])
print(stats)
print("min of stats",np.min(stats))
print("max of stats",np.max(stats))
print("min of stats axis=1",np.min(stats,axis=1))
print("max of stats axis=1",np.max(stats,axis=1))
print("sum of stats",np.sum(stats))


[[1 2 3]
 [4 5 6]]
min of stats 1
max of stats 6
min of stats axis=1 [1 4]
max of stats axis=1 [3 6]
sum of stats 21


### Reorganizatio of Arrays

In [13]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print("Original array:")
print(before)
after=before.reshape((2,2,2))
print("After reshaping:")
print(after)


Original array:
[[1 2 3 4]
 [5 6 7 8]]
After reshaping:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Verticaly stacking Vectors

In [14]:
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print("Vertical Stack")
print(np.vstack([v1,v2]))
print("Horizontal Stack")
print(np.hstack([v1,v2]))
print("Vertical Stack")
print(np.vstack([v1,v2,v1,v2]))
print("Horizontal Stack")
print(np.hstack([v1,v2,v1,v2]))

Vertical Stack
[[1 2 3 4]
 [5 6 7 8]]
Horizontal Stack
[1 2 3 4 5 6 7 8]
Vertical Stack
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
Horizontal Stack
[1 2 3 4 5 6 7 8 1 2 3 4 5 6 7 8]


In [15]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
print("Horizontal Stack")
print(np.hstack((h1,h2)))

Horizontal Stack
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [18]:
randomIntArray2=np.random.randint(1,7,size=(3,3))
print(randomIntArray2)
((randomIntArray2>3)&(randomIntArray2<6))

[[1 5 2]
 [2 2 3]
 [5 2 6]]


array([[False,  True, False],
       [False, False, False],
       [ True, False, False]])