### **Fundamentals of Py Tourch**
- `Resource Note Book` : [Resource Notebook](https://www.learnpytorch.io/00_pytorch_fundamentals/)

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.6.0+cpu


### Introduction To Tensor

#### Creating Tensor


In [3]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [4]:
dimention_of_tensor=scalar.ndim
print(dimention_of_tensor)

0


In [5]:
### Get tensor back as python Int
item_in_tensor=scalar.item()
print(item_in_tensor)

7


In [6]:
### Vector
vector = torch.tensor([1, 2, 3])
print(vector)

tensor([1, 2, 3])


In [7]:
### vector Dimension
dimention_of_tensor=vector.ndim
print(dimention_of_tensor)

1


In [8]:
### shape of the tensor
tensor_shape  = vector.shape
print(tensor_shape)

torch.Size([3])


In [9]:
#   MATRIX
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(MATRIX)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [10]:
dimention_of_tensor = MATRIX.ndim
print(dimention_of_tensor)

2


In [11]:
shape_of_tensor=MATRIX.shape
print(shape_of_tensor)

torch.Size([2, 3])


In [12]:
print(MATRIX[1])

tensor([4, 5, 6])


In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [14]:
# dimension of the tensor
dimention_of_tensor = TENSOR.ndim
print(dimention_of_tensor)

3


In [15]:
# shape of the tensor
shape_of_tensor = TENSOR.shape
print(shape_of_tensor)

torch.Size([3, 3, 3])


In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
- `why Random Tensors?`
- `Random Tensors` are important because the way many neural networks learns is that they start with tensors full of random numbers and then adjust the numbers to get to better representations of the data.

`start with random numbers -> look at the daat -> update the random numbers -> look at the data -> update the random numbers`

In [17]:
# create a random tensor of size 3x4
random_tensor = torch.rand(3)
print(random_tensor,"\n")
random_tensor = torch.rand(3, 4)
print(random_tensor,"\n")
random_tensor = torch.rand(3, 4, 5)
print(random_tensor,"\n")
random_tensor = torch.rand(3, 4, 5, 6)
print(random_tensor,"\n")

tensor([0.8573, 0.8695, 0.6584]) 

tensor([[0.0137, 0.2160, 0.6846, 0.6053],
        [0.0383, 0.4277, 0.2673, 0.6275],
        [0.4148, 0.1008, 0.4428, 0.1574]]) 

tensor([[[0.3227, 0.7477, 0.2893, 0.1450, 0.2327],
         [0.1681, 0.4584, 0.6166, 0.9294, 0.8973],
         [0.3817, 0.4783, 0.3715, 0.0868, 0.0258],
         [0.5055, 0.8391, 0.4051, 0.0537, 0.3800]],

        [[0.4414, 0.4638, 0.5818, 0.6957, 0.8388],
         [0.2378, 0.4486, 0.9509, 0.3383, 0.0340],
         [0.9301, 0.3331, 0.1141, 0.7130, 0.7564],
         [0.6998, 0.7915, 0.7777, 0.7416, 0.1787]],

        [[0.2900, 0.2431, 0.6604, 0.3881, 0.6860],
         [0.8744, 0.8148, 0.9859, 0.3594, 0.8508],
         [0.4375, 0.6035, 0.8534, 0.4687, 0.7063],
         [0.1882, 0.0512, 0.3985, 0.4280, 0.8007]]]) 

tensor([[[[0.3751, 0.2809, 0.9818, 0.2421, 0.8181, 0.1449],
          [0.3819, 0.9787, 0.2511, 0.1918, 0.5582, 0.4199],
          [0.0236, 0.9274, 0.5721, 0.7735, 0.9267, 0.9164],
          [0.0521, 0.2305, 0.4164, 0

In [18]:
# create a random tensor with similar shape to an image tensor
random_tensor_image_size_tensor = torch.randn(size=(3,224, 224)) #height, width, color channels(R, G, B)
# random_tensor_image_size_tensor = torch.randn(3,224, 224) #height, width, color channels(R, G, B)
random_tensor_image_size_tensor.shape, random_tensor_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones


In [19]:
# Create a ensors of all zeros
zero = torch.zeros(3,4)
print(zero)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [20]:
random_tensor = torch.rand(3,4)
print(zero*random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [21]:
ones = torch.ones(4, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Creating a Range of tensors and tensors-like objects

In [22]:
# use torch.range()
one_to_ten = torch.range(1, 10)
print(one_to_ten)
one_to_ten = torch.arange(start= 0, end=78, step=11)
print(one_to_ten)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([ 0, 11, 22, 33, 44, 55, 66, 77])


C:\Users\DHUSNIC INFANT DM\AppData\Local\Temp\ipykernel_19344\3818570455.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(1, 10)


In [23]:
# Creating a tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes
#### Defnitions

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

> **Note:** An integer is a flat round number like `7` whereas a float has a decimal `7.0`.
1. **check For the correct datatype**
2. **check for the correct shape**
3. **check for the correct device**


The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

> **Resources:** 
  * See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Read the [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the `dtype` parameter.

In [24]:
### Float 32 tensor
## Important paprameters as dtype, device, and requires_grad
float_32_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0],dtype=None)
print(float_32_tensor.dtype)
float_16_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0],dtype=torch.float16)
print(float_16_tensor.dtype)
float_64_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0],
                               dtype=torch.float64, #What data type is the tensor (e.g. flaoat32, float16, float64, int8, int16, int32, int64, bool)
                               device="cpu",        #Where the tensor is stored (e.g. cpu, gpu)
                               requires_grad=True   #Whether or not we need to track gradients with this tensor operations (e.g. True, False)
                               )

print(float_64_tensor.dtype)

torch.float32
torch.float16
torch.float64


In [25]:
float_16_tensor = float_64_tensor.type(torch.float16)
print(float_16_tensor.dtype)

torch.float16


In [26]:
mult = float_16_tensor*float_32_tensor
print(mult.dtype)

torch.float32


In [27]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float32)
print(int_32_tensor)
mult = int_32_tensor*float_32_tensor
print(mult,mult.dtype)

tensor([3, 6, 9], dtype=torch.int32)
tensor([ 9., 36., 81.]) torch.float32


### Check for the Information of Tensor
1. **check For the correct datatype**
2. **check for the correct shape**
3. **check for the correct device**

In [28]:
# Create a tensor
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor  :   {some_tensor.dtype}")
print(f"Shape of tensor     :   {some_tensor.shape}")
print(f"Device tensor is on :   {some_tensor.device}")

tensor([[0.9563, 0.7839, 0.5575, 0.3343],
        [0.2761, 0.0580, 0.0544, 0.1067],
        [0.8329, 0.0746, 0.8396, 0.4097]])
Datatype of tensor  :   torch.float32
Shape of tensor     :   torch.Size([3, 4])
Device tensor is on :   cpu


### **Manuipulating Tensors (tensor manipulation)**

**Tensors are Operations Including**:
- Addtion
- Subtraction
- Multiplication
- Division
- Matrix Multiplication

In [29]:
# Create a tensor with a single dimension
tensor  = torch.tensor([1, 2, 3])
print(tensor)

# Tesnsor with Addition, Subtraction, Multiplication
print(tensor+10) # Add 10 to each element in the tensor
# print(torch.add(tensor, 10)) # Add 10 to each element in the tensor
print(tensor-10) # Subtract 10 from each element in the tensor
# print(torch.sub(tensor, 10)) # Subtract 10 from each element in the tensor
print(tensor*10) # Multiply each element in the tensor by 10
# print(torch.mul(tensor, 10)) # Multiply each element in the tensor by 10
print(tensor/10,tensor//10) # Divide each element in the tensor by 10
# print(torch.div(tensor, 10)) # Divide each element in the tensor by 10

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000]) tensor([0, 0, 0])


In [30]:
### Transpose of a tensor
Matrix = torch.tensor([[1,2,3],
                       [4,5,6],])

print(Matrix,"\n",Matrix.shape,"\n")
print("\n",Matrix.T,"\n",Matrix.T.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) 
 torch.Size([2, 3]) 


 tensor([[1, 4],
        [2, 5],
        [3, 6]]) 
 torch.Size([3, 2])


In [31]:
%%time
tensor=torch.tensor([1,2,3])
print(tensor @ tensor)

tensor(14)
CPU times: total: 0 ns
Wall time: 1.01 ms


In [32]:
# Tensor of Matrix Multiplication
X = torch.rand(1,3)
print(f"X   :   {X}","\n")
Y = torch.rand(3, 1)
print(f"Y   :  {Y}","\n")
print(f"X * X.T   :   {torch.matmul(X,X.T)}",X.shape,"\n") # Matrix Multiplication
print(f"Y * Y.T   :   {torch.matmul(Y,Y.T)}",Y.shape,"\n") # Matrix Multiplication
print(f"X * Y   :   {X.mm(Y)}","\n") # Matrix Multiplication
# print(f"X * Y   :   {torch.mm(X, Y)}","\n") # Matrix Multiplication
# print(f"X * Y   :   {X @ Y}","\n") # Matrix Multiplication

X   :   tensor([[0.7396, 0.2467, 0.4329]]) 

Y   :  tensor([[0.4122],
        [0.2511],
        [0.4169]]) 

X * X.T   :   tensor([[0.7953]]) torch.Size([1, 3]) 

Y * Y.T   :   tensor([[0.1699, 0.1035, 0.1718],
        [0.1035, 0.0631, 0.1047],
        [0.1718, 0.1047, 0.1738]]) torch.Size([3, 1]) 

X * Y   :   tensor([[0.5473]]) 



### One of the most Common errors in deep learning is the "Shape Mismatch" error.

In [33]:
### Shapes for Matrix Multiplication
tensor_A  = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])
tensor_B  = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])
print(tensor_A.shape, tensor_B.shape,"\n")
try:
    print(f"tensor_A @ tensor_B :  ","\n",tensor_A @ tensor_B)
except Exception as e:
    print(e)
    print(f"tensor_A @ tensor_B.T :  ","\n",tensor_A @ tensor_B.T)

torch.Size([3, 2]) torch.Size([3, 2]) 

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
tensor_A @ tensor_B.T :   
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### Finding the Aggregation of Tensors
- Min
- Max
- Mean
- Sum

In [34]:
tensor = torch.arange(0,100,10)
print(tensor , tensor.shape)
print(f"Min of tesnsor: {tensor.min()}")
print(f"Max of tesnsor: {tensor.max()}")
print(f"Sum of tesnsor: {tensor.sum()}")
try:
    print(f"Mean of tesnsor: {tensor.mean()}")
except Exception as e:
    print(e,"\n But its ",tensor.dtype,"\n")
    tensor = tensor.type(torch.float32)
    print(f"Mean of tesnsor: {tensor.mean()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.Size([10])
Min of tesnsor: 0
Max of tesnsor: 90
Sum of tesnsor: 450
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long 
 But its  torch.int64 

Mean of tesnsor: 45.0


### Finding the Positional Min and Max of a Tensor
- Find the position of the maximum and minimum values in a tensor

In [35]:
tensor = torch.randint(1, 100,(1,10))
print(tensor)
print(f"Position or Index of the Element which has Minimum Value :  {tensor.argmin()}")
print(f"Position or Index of the Element which has Maximum Value :  {tensor.argmax()}")


tensor([[17,  8, 89, 88,  6, 82, 76, 29, 94, 75]])
Position or Index of the Element which has Minimum Value :  4
Position or Index of the Element which has Maximum Value :  8


### Reshaping, Stacking, Squeezing and Unsqueezing tensors
* `Reshaping` - Changing the shape of the tensor to desired shape

* `View` - Viewing the tensor as a new shape but keep the same memory as the original tensor

* `Stacking` - Combining multiple tensors on top of each other (vstack) or side by side (hstack) or depth wise (dstack)

* `Squeezing` - Removing all 1 dimensions from a tensor

* `Unsqueezing` - Adding an extra dimension to a tensor

* `Permute` - Return a view of the original tensor with its dimensions permuted (swapped) in a certain way

In [36]:
# Creation of a tensor
tensor = torch.arange(1,200,10)
print(tensor,"\n",tensor.shape)


tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191]) 
 torch.Size([20])


In [37]:
# Reshape the input data
tensor_input_reshaped = torch.reshape(tensor, (2,10))
print(tensor_input_reshaped, "\n", tensor_input_reshaped.shape)
print(tensor, "\n", tensor.shape,"\n")
tensor.reshape(2,10)
print(tensor, "\n", tensor.shape,"\n")

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
        [101, 111, 121, 131, 141, 151, 161, 171, 181, 191]]) 
 torch.Size([2, 10])
tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191]) 
 torch.Size([20]) 

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191]) 
 torch.Size([20]) 



In [38]:
#Change the View
View=tensor.view(2,10)
print(View,"\n",View.shape)

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
        [101, 111, 121, 131, 141, 151, 161, 171, 181, 191]]) 
 torch.Size([2, 10])


In [39]:
### Stack tensors on top of each other, and create a new tensor of size 3x4
# vstack=torch.vstack([tensor, tensor, tensor])
vstack=torch.stack([tensor, tensor, tensor], dim=0)
print(vstack, '\n', vstack.shape)
# vstack=torch.hstack([tensor, tensor, tensor])
hstack=torch.stack([tensor, tensor, tensor], dim=1)
print(hstack, '\n', hstack.shape)
try:
    # vstack=torch.dstack([tensor, tensor, tensor])
    dstack=torch.stack([tensor, tensor, tensor], dim=2)
    print(dstack, '\n', dstack.shape)
except Exception as e:
    print(e)

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191],
        [  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191],
        [  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191]]) 
 torch.Size([3, 20])
tensor([[  1,   1,   1],
        [ 11,  11,  11],
        [ 21,  21,  21],
        [ 31,  31,  31],
        [ 41,  41,  41],
        [ 51,  51,  51],
        [ 61,  61,  61],
        [ 71,  71,  71],
        [ 81,  81,  81],
        [ 91,  91,  91],
        [101, 101, 101],
        [111, 111, 111],
        [121, 121, 121],
        [131, 131, 131],
        [141, 141, 141],
        [151, 151, 151],
        [161, 161, 161],
        [171, 171, 171],
        [181, 181, 181],
        [191, 191, 191]]) 
 torch.Size([20, 3])
Dimension out of range (expected to be in range of [-2, 1], but got 2)


In [40]:
# tourch.squeeze() - removes all single dimensions from a target tensor
X = torch.zeros(2, 1, 2, 1, 2)
print(X.size(),"\n")
Y = torch.squeeze(X)
print(Y.size(),"\n")
Y = torch.squeeze(X, 0)
print(Y.size(),"\n")
Y = torch.squeeze(X, 1)
print(Y.size(),"\n")



X = torch.randint(1, 10, (1,9))
print(f"Previous tensor: {X}")
print(f"Shape Of X: {X.shape}","\n")
print(f"Tensor after squeeze: {torch.squeeze(X)}")
print(f"Shape Of X after squeeze: {torch.squeeze(X).shape}")


torch.Size([2, 1, 2, 1, 2]) 

torch.Size([2, 2, 2]) 

torch.Size([2, 1, 2, 1, 2]) 

torch.Size([2, 2, 1, 2]) 

Previous tensor: tensor([[7, 7, 8, 1, 4, 2, 7, 3, 7]])
Shape Of X: torch.Size([1, 9]) 

Tensor after squeeze: tensor([7, 7, 8, 1, 4, 2, 7, 3, 7])
Shape Of X after squeeze: torch.Size([9])


In [41]:
# tourch.unsqueeze() - adds a single dimension to a tensor at a specified dimension
X = torch.tensor([1,2,3,4])
print(f"Previous target: {X}")
print(f"Previous shape: {X.shape}","\n")
# Add an extra dimension to X
X_expanded = X.unsqueeze(dim=0)
print(f"New target: {X_expanded}")
print(f"New shape: {X_expanded.shape}","\n")

X_expanded = X.unsqueeze(dim=1)
print(f"New target: {X_expanded}")
print(f"New shape: {X_expanded.shape}")


Previous target: tensor([1, 2, 3, 4])
Previous shape: torch.Size([4]) 

New target: tensor([[1, 2, 3, 4]])
New shape: torch.Size([1, 4]) 

New target: tensor([[1],
        [2],
        [3],
        [4]])
New shape: torch.Size([4, 1])


In [42]:
# tourch.permute() - to change the order of the dimensions of a tensor
X = torch.randn(2, 3, 5)
print(f"X : {X}")
print(f"Shape of X : {X.shape}","\n")
X_permuted = X.permute(2, 0, 1)
print(f"X_permuted : {X_permuted}")
print(f"Shape X_permuted : {X_permuted.shape}","\n\n")



# torch-permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # [colour channels, height, width]

X : tensor([[[ 2.3702, -1.2116,  0.4407,  0.3191, -0.1280],
         [-0.4688, -0.8344, -2.7497, -0.0622, -0.1323],
         [ 0.0621, -0.5909, -0.2193, -0.8160, -1.2861]],

        [[-1.1370, -0.3983, -2.7680,  1.4871,  1.3792],
         [ 1.1238, -0.0144,  0.3005, -0.0344,  1.5291],
         [ 1.6074, -0.9067,  1.1236,  0.5800,  0.8567]]])
Shape of X : torch.Size([2, 3, 5]) 

X_permuted : tensor([[[ 2.3702, -0.4688,  0.0621],
         [-1.1370,  1.1238,  1.6074]],

        [[-1.2116, -0.8344, -0.5909],
         [-0.3983, -0.0144, -0.9067]],

        [[ 0.4407, -2.7497, -0.2193],
         [-2.7680,  0.3005,  1.1236]],

        [[ 0.3191, -0.0622, -0.8160],
         [ 1.4871, -0.0344,  0.5800]],

        [[-0.1280, -0.1323, -1.2861],
         [ 1.3792,  1.5291,  0.8567]]])
Shape X_permuted : torch.Size([5, 2, 3]) 


Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing
- Indexing with PyTourch is similar to indexing with NumPy

In [43]:
x = torch.arange(1, 10).reshape(1,3, 3)
print(f"x: {x}, shape: {x.shape}")

x: tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]), shape: torch.Size([1, 3, 3])


In [44]:
print(f"x[0] = {x[0]}","\n")
print(f"x[0][0] = {x[0][0]}","\n")
print(f"x[0][0][0] = {x[0][0][0]}","\n")

x[0] = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 

x[0][0] = tensor([1, 2, 3]) 

x[0][0][0] = 1 



In [45]:
# you can also use ":" to select a all of target dimension
print(f"x[0, :] = {x[0, :]}","\n")
print(f"x[:, :, 1] = {x[:,: ,1]}")

x[0, :] = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) 

x[:, :, 1] = tensor([[2, 5, 8]])


In [46]:
# Get all vlues of the 0 dimention but only the 1 index value of 1st and 2nd dimention
print(x[0,1,2])
print(x[0,2,2])
print(x[:,:,2])

tensor(6)
tensor(9)
tensor([[3, 6, 9]])


### PyTorch tensors & Numpy
Numpy is a popular library for scientific computing that uses multi-dimensional arrays and matrices.

And because of this , PyTorch has functionality to intract with it.

- Data in NumPy , Want in PyTorch tensor
- NumPy array -> PyTorch Tensor -> `torch.from_numpy(ndarray)`

- PyTorch Tensor -> NumPy array -> `tensor.numpy()`

In [47]:
# NumPy array to tensor

array = np.array([1, 2, 3, 4, 5])
converted_tensor = torch.from_numpy(array)
tensor = torch.tensor([1, 2, 3, 4, 5])
print(f"Array: {array}")
print(f"Tensor: {converted_tensor}")
print(f"Converted Tensor type: {converted_tensor.dtype}, Tensor type: {tensor.dtype}")

Array: [1 2 3 4 5]
Tensor: tensor([1, 2, 3, 4, 5])
Converted Tensor type: torch.int64, Tensor type: torch.int64


In [48]:
# Tensor to Numpy array
tensor  = torch.ones(5, 3)
numpy_tensor = tensor.numpy()
print(f"tensor: {tensor}")
print(f"numpy_tensor: {numpy_tensor}")

tensor: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
numpy_tensor: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### PyTorch Reproducbility
In Short how neural networks are trained

`start with a random number -> tensor  operatons -> random number to try and make them of the data -> repeat`

- TO Reduce the randomness we can use the concept Called the  **random seed** `torch.manual_seed(seed)`

Essentially What the random seed does it "flavour" the randomness


In [49]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A,"\n")
print(random_tensor_B,"\n")
print(random_tensor_A == random_tensor_B)

tensor([[0.5638, 0.7477, 0.3954, 0.0400],
        [0.3132, 0.4225, 0.0356, 0.3231],
        [0.8651, 0.2833, 0.8869, 0.6871]]) 

tensor([[0.2623, 0.5016, 0.2028, 0.3039],
        [0.7884, 0.5488, 0.4925, 0.7898],
        [0.9974, 0.3072, 0.1125, 0.9264]]) 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [50]:
# Lets Make some Random but reproducible data
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)
random_tensor_D = torch.rand(3,4)
print(f"Random Tensor C:\n {random_tensor_C} \n")
print(f"Random Tensor D:\n {random_tensor_D} \n")
print(f"Random Tensor SEED :\n {random_tensor_C == random_tensor_D} \n")


Random Tensor C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

Random Tensor D:
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]]) 

Random Tensor SEED :
 tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]) 



In [51]:
# Lets Make some Random but reproducible data
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(f"Random Tensor C:\n {random_tensor_C} \n")
print(f"Random Tensor D:\n {random_tensor_D} \n")
print(f"Random Tensor SEED :\n {random_tensor_C == random_tensor_D} \n")


Random Tensor C:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

Random Tensor D:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 

Random Tensor SEED :
 tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]]) 



### Running tensors on GPUs (and making faster computations)

- Deep learning algorithms require a lot of numerical operations.

- And by default these operations are often done on a CPU (computer processing unit).

- However, there's another common piece of hardware called a GPU (graphics processing unit), which is often much faster at performing the specific types of operations neural networks need (matrix multiplications) than CPUs.

Your computer might have one.

If so, you should look to use it whenever you can to train neural networks because chances are it'll speed up the training time dramatically.

There are a few ways to first get access to a GPU and secondly get PyTorch to use the GPU.

Note: When I reference "GPU" throughout this course, I'm referencing a Nvidia GPU with CUDA enabled (CUDA is a computing platform and API that helps allow GPUs be used for general purpose computing & not just graphics) unless otherwise specified.

In [52]:
torch.cuda.is_available()

False

In [53]:
torch.cuda.device_count()

0