### **Fundamentals of Py Tourch**
- `Resource Note Book` : [Resource Notebook](https://www.learnpytorch.io/00_pytorch_fundamentals/)

In [123]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [124]:
print(torch.__version__)

2.6.0+cpu


### Introduction To Tensor

#### Creating Tensor


In [125]:
# scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [126]:
dimention_of_tensor=scalar.ndim
print(dimention_of_tensor)

0


In [127]:
### Get tensor back as python Int
item_in_tensor=scalar.item()
print(item_in_tensor)

7


In [128]:
### Vector
vector = torch.tensor([1, 2, 3])
print(vector)

tensor([1, 2, 3])


In [129]:
### vector Dimension
dimention_of_tensor=vector.ndim
print(dimention_of_tensor)

1


In [130]:
### shape of the tensor
tensor_shape  = vector.shape
print(tensor_shape)

torch.Size([3])


In [131]:
#   MATRIX
MATRIX = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(MATRIX)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [132]:
dimention_of_tensor = MATRIX.ndim
print(dimention_of_tensor)

2


In [133]:
shape_of_tensor=MATRIX.shape
print(shape_of_tensor)

torch.Size([2, 3])


In [134]:
print(MATRIX[1])

tensor([4, 5, 6])


In [135]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(TENSOR)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [136]:
# dimension of the tensor
dimention_of_tensor = TENSOR.ndim
print(dimention_of_tensor)

3


In [137]:
# shape of the tensor
shape_of_tensor = TENSOR.shape
print(shape_of_tensor)

torch.Size([3, 3, 3])


In [138]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

### Random Tensors
- `why Random Tensors?`
- `Random Tensors` are important because the way many neural networks learns is that they start with tensors full of random numbers and then adjust the numbers to get to better representations of the data.

`start with random numbers -> look at the daat -> update the random numbers -> look at the data -> update the random numbers`

In [139]:
# create a random tensor of size 3x4
random_tensor = torch.rand(3)
print(random_tensor,"\n")
random_tensor = torch.rand(3, 4)
print(random_tensor,"\n")
random_tensor = torch.rand(3, 4, 5)
print(random_tensor,"\n")
random_tensor = torch.rand(3, 4, 5, 6)
print(random_tensor,"\n")

tensor([0.9634, 0.3308, 0.4765]) 

tensor([[0.7991, 0.0266, 0.7598, 0.8452],
        [0.3241, 0.2486, 0.9242, 0.0346],
        [0.0950, 0.3053, 0.2937, 0.4281]]) 



tensor([[[0.7644, 0.9355, 0.3790, 0.8273, 0.5843],
         [0.9313, 0.8647, 0.0773, 0.0648, 0.2910],
         [0.6214, 0.3627, 0.2522, 0.9251, 0.5422],
         [0.1934, 0.3393, 0.9784, 0.4427, 0.2298]],

        [[0.5311, 0.7109, 0.5757, 0.3472, 0.3057],
         [0.3667, 0.0857, 0.7713, 0.2030, 0.6681],
         [0.1207, 0.6677, 0.0043, 0.1243, 0.1808],
         [0.6428, 0.8721, 0.2453, 0.1911, 0.3580]],

        [[0.5587, 0.6700, 0.2301, 0.5289, 0.7726],
         [0.1227, 0.5683, 0.8849, 0.0738, 0.4899],
         [0.1413, 0.1096, 0.2738, 0.4034, 0.3395],
         [0.7497, 0.2066, 0.2459, 0.7123, 0.2069]]]) 

tensor([[[[1.3688e-01, 4.2908e-01, 3.0124e-01, 4.7997e-01, 7.8040e-01,
           6.6925e-01],
          [2.8878e-01, 5.6571e-01, 6.9942e-01, 5.4226e-01, 5.6897e-01,
           9.1254e-01],
          [7.7844e-01, 8.6141e-01, 3.0411e-01, 8.8946e-01, 4.7485e-01,
           7.8311e-01],
          [4.4500e-01, 7.0673e-01, 9.5547e-02, 4.1246e-01, 3.0960e-01,
           6.3868e-01],


In [140]:
# create a random tensor with similar shape to an image tensor
random_tensor_image_size_tensor = torch.randn(size=(3,224, 224)) #height, width, color channels(R, G, B)
# random_tensor_image_size_tensor = torch.randn(3,224, 224) #height, width, color channels(R, G, B)
random_tensor_image_size_tensor.shape, random_tensor_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and Ones


In [141]:
# Create a ensors of all zeros
zero = torch.zeros(3,4)
print(zero)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [142]:
random_tensor = torch.rand(3,4)
print(zero*random_tensor)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [143]:
ones = torch.ones(4, 4)
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


### Creating a Range of tensors and tensors-like objects

In [144]:
# use torch.range()
one_to_ten = torch.range(1, 10)
print(one_to_ten)
one_to_ten = torch.arange(start= 0, end=78, step=11)
print(one_to_ten)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([ 0, 11, 22, 33, 44, 55, 66, 77])


C:\Users\DHUSNIC INFANT DM\AppData\Local\Temp\ipykernel_3500\3818570455.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(1, 10)


In [145]:
# Creating a tensor like
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([0, 0, 0, 0, 0, 0, 0, 0])


### Tensor datatypes
#### Defnitions

There are many different [tensor datatypes available in PyTorch](https://pytorch.org/docs/stable/tensors.html#data-types).

Some are specific for CPU and some are better for GPU.

Getting to know which one can take some time.

Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is `torch.float32` or `torch.float`.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (`torch.float16` or `torch.half`) and 64-bit floating point (`torch.float64` or `torch.double`).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

Plus more!

> **Note:** An integer is a flat round number like `7` whereas a float has a decimal `7.0`.
1. **check For the correct datatype**
2. **check for the correct shape**
3. **check for the correct device**


The reason for all of these is to do with **precision in computing**.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

> **Resources:** 
  * See the [PyTorch documentation for a list of all available tensor datatypes](https://pytorch.org/docs/stable/tensors.html#data-types).
  * Read the [Wikipedia page for an overview of what precision in computing](https://en.wikipedia.org/wiki/Precision_(computer_science)) is.

Let's see how to create some tensors with specific datatypes. We can do so using the `dtype` parameter.

In [146]:
### Float 32 tensor
## Important paprameters as dtype, device, and requires_grad
float_32_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0],dtype=None)
print(float_32_tensor.dtype)
float_16_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0],dtype=torch.float16)
print(float_16_tensor.dtype)
float_64_tensor = torch.tensor([1.0, 2.0, 3.0, 4.0],
                               dtype=torch.float64, #What data type is the tensor (e.g. flaoat32, float16, float64, int8, int16, int32, int64, bool)
                               device="cpu",        #Where the tensor is stored (e.g. cpu, gpu)
                               requires_grad=True   #Whether or not we need to track gradients with this tensor operations (e.g. True, False)
                               )

print(float_64_tensor.dtype)

torch.float32
torch.float16
torch.float64


In [147]:
float_16_tensor = float_64_tensor.type(torch.float16)
print(float_16_tensor.dtype)

torch.float16


In [148]:
mult = float_16_tensor*float_32_tensor
print(mult.dtype)

torch.float32


In [149]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype=torch.float32)
print(int_32_tensor)
mult = int_32_tensor*float_32_tensor
print(mult,mult.dtype)

tensor([3, 6, 9], dtype=torch.int32)
tensor([ 9., 36., 81.]) torch.float32


### Check for the Information of Tensor
1. **check For the correct datatype**
2. **check for the correct shape**
3. **check for the correct device**

In [150]:
# Create a tensor
some_tensor = torch.rand(3,4)
print(some_tensor)
print(f"Datatype of tensor  :   {some_tensor.dtype}")
print(f"Shape of tensor     :   {some_tensor.shape}")
print(f"Device tensor is on :   {some_tensor.device}")

tensor([[0.7232, 0.5364, 0.8280, 0.8340],
        [0.9019, 0.5742, 0.6583, 0.0276],
        [0.3037, 0.0159, 0.8371, 0.0493]])
Datatype of tensor  :   torch.float32
Shape of tensor     :   torch.Size([3, 4])
Device tensor is on :   cpu


### **Manuipulating Tensors (tensor manipulation)**

**Tensors are Operations Including**:
- Addtion
- Subtraction
- Multiplication
- Division
- Matrix Multiplication

In [151]:
# Create a tensor with a single dimension
tensor  = torch.tensor([1, 2, 3])
print(tensor)

# Tesnsor with Addition, Subtraction, Multiplication
print(tensor+10) # Add 10 to each element in the tensor
# print(torch.add(tensor, 10)) # Add 10 to each element in the tensor
print(tensor-10) # Subtract 10 from each element in the tensor
# print(torch.sub(tensor, 10)) # Subtract 10 from each element in the tensor
print(tensor*10) # Multiply each element in the tensor by 10
# print(torch.mul(tensor, 10)) # Multiply each element in the tensor by 10
print(tensor/10,tensor//10) # Divide each element in the tensor by 10
# print(torch.div(tensor, 10)) # Divide each element in the tensor by 10

tensor([1, 2, 3])
tensor([11, 12, 13])
tensor([-9, -8, -7])
tensor([10, 20, 30])
tensor([0.1000, 0.2000, 0.3000]) tensor([0, 0, 0])


In [152]:
### Transpose of a tensor
Matrix = torch.tensor([[1,2,3],
                       [4,5,6],])

print(Matrix,"\n",Matrix.shape,"\n")
print("\n",Matrix.T,"\n",Matrix.T.shape)

tensor([[1, 2, 3],
        [4, 5, 6]]) 
 torch.Size([2, 3]) 


 tensor([[1, 4],
        [2, 5],
        [3, 6]]) 
 torch.Size([3, 2])


In [153]:
%%time
tensor=torch.tensor([1,2,3])
print(tensor @ tensor)

tensor(14)
CPU times: total: 0 ns
Wall time: 1.15 ms


In [154]:
# Tensor of Matrix Multiplication
X = torch.rand(1,3)
print(f"X   :   {X}","\n")
Y = torch.rand(3, 1)
print(f"Y   :  {Y}","\n")
print(f"X * X.T   :   {torch.matmul(X,X.T)}",X.shape,"\n") # Matrix Multiplication
print(f"Y * Y.T   :   {torch.matmul(Y,Y.T)}",Y.shape,"\n") # Matrix Multiplication
print(f"X * Y   :   {X.mm(Y)}","\n") # Matrix Multiplication
# print(f"X * Y   :   {torch.mm(X, Y)}","\n") # Matrix Multiplication
# print(f"X * Y   :   {X @ Y}","\n") # Matrix Multiplication

X   :   tensor([[0.7498, 0.4429, 0.3368]]) 

Y   :  tensor([[0.1369],
        [0.4761],
        [0.2995]]) 

X * X.T   :   tensor([[0.8717]]) torch.Size([1, 3]) 

Y * Y.T   :   tensor([[0.0187, 0.0652, 0.0410],
        [0.0652, 0.2266, 0.1426],
        [0.0410, 0.1426, 0.0897]]) torch.Size([3, 1]) 

X * Y   :   tensor([[0.4143]]) 



### One of the most Common errors in deep learning is the "Shape Mismatch" error.

In [155]:
### Shapes for Matrix Multiplication
tensor_A  = torch.tensor([[1,2],
                          [3,4],
                          [5,6]])
tensor_B  = torch.tensor([[7,10],
                          [8,11],
                          [9,12]])
print(tensor_A.shape, tensor_B.shape,"\n")
try:
    print(f"tensor_A @ tensor_B :  ","\n",tensor_A @ tensor_B)
except Exception as e:
    print(e)
    print(f"tensor_A @ tensor_B.T :  ","\n",tensor_A @ tensor_B.T)

torch.Size([3, 2]) torch.Size([3, 2]) 

mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)
tensor_A @ tensor_B.T :   
 tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


### Finding the Aggregation of Tensors
- Min
- Max
- Mean
- Sum

In [163]:
tensor = torch.arange(0,100,10)
print(tensor , tensor.shape)
print(f"Min of tesnsor: {tensor.min()}")
print(f"Max of tesnsor: {tensor.max()}")
print(f"Sum of tesnsor: {tensor.sum()}")
try:
    print(f"Mean of tesnsor: {tensor.mean()}")
except Exception as e:
    print(e,"\n But its ",tensor.dtype,"\n")
    tensor = tensor.type(torch.float32)
    print(f"Mean of tesnsor: {tensor.mean()}")

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.Size([10])
Min of tesnsor: 0
Max of tesnsor: 90
Sum of tesnsor: 450
mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long 
 But its  torch.int64 

Mean of tesnsor: 45.0


### Finding the Positional Min and Max of a Tensor
- Find the position of the maximum and minimum values in a tensor

In [168]:
tensor = torch.randint(1, 100,(1,10))
print(tensor)
print(f"Position or Index of the Element which has Minimum Value :  {tensor.argmin()}")
print(f"Position or Index of the Element which has Maximum Value :  {tensor.argmax()}")


tensor([[92, 45, 89,  4, 55, 18, 73, 67, 94, 88]])
Position or Index of the Element which has Minimum Value :  3
Position or Index of the Element which has Maximum Value :  8


### Reshaping, Stacking, Squeezing and Unsqueezing tensors
* `Reshaping` - Changing the shape of the tensor to desired shape

* `View` - Viewing the tensor as a new shape but keep the same memory as the original tensor

* `Stacking` - Combining multiple tensors on top of each other (vstack) or side by side (hstack) or depth wise (dstack)

* `Squeezing` - Removing all 1 dimensions from a tensor

* `Unsqueezing` - Adding an extra dimension to a tensor

* `Permute` - Return a view of the original tensor with its dimensions permuted (swapped) in a certain way

In [176]:
# Creation of a tensor
tensor = torch.arange(1,200,10)
print(tensor,"\n",tensor.shape)


tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191]) 
 torch.Size([20])


In [182]:
# Reshape the input data
tensor_input_reshaped = torch.reshape(tensor, (2,10))
print(tensor_input_reshaped, "\n", tensor_input_reshaped.shape)
print(tensor, "\n", tensor.shape,"\n")
tensor.reshape(2,10)
print(tensor, "\n", tensor.shape,"\n")

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
        [101, 111, 121, 131, 141, 151, 161, 171, 181, 191]]) 
 torch.Size([2, 10])
tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191]) 
 torch.Size([20]) 

tensor([  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
        141, 151, 161, 171, 181, 191]) 
 torch.Size([20]) 



In [185]:
#Change the View
View=tensor.view(2,10)
print(View,"\n",View.shape)

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
        [101, 111, 121, 131, 141, 151, 161, 171, 181, 191]]) 
 torch.Size([2, 10])


In [192]:
### Stack tensors on top of each other, and create a new tensor of size 3x4
# vstack=torch.vstack([tensor, tensor, tensor])
vstack=torch.stack([tensor, tensor, tensor], dim=0)
print(vstack, '\n', vstack.shape)
# vstack=torch.hstack([tensor, tensor, tensor])
hstack=torch.stack([tensor, tensor, tensor], dim=1)
print(hstack, '\n', hstack.shape)
try:
    # vstack=torch.dstack([tensor, tensor, tensor])
    dstack=torch.stack([tensor, tensor, tensor], dim=2)
    print(dstack, '\n', dstack.shape)
except Exception as e:
    print(e)

tensor([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191],
        [  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191],
        [  1,  11,  21,  31,  41,  51,  61,  71,  81,  91, 101, 111, 121, 131,
         141, 151, 161, 171, 181, 191]]) 
 torch.Size([3, 20])
tensor([[  1,   1,   1],
        [ 11,  11,  11],
        [ 21,  21,  21],
        [ 31,  31,  31],
        [ 41,  41,  41],
        [ 51,  51,  51],
        [ 61,  61,  61],
        [ 71,  71,  71],
        [ 81,  81,  81],
        [ 91,  91,  91],
        [101, 101, 101],
        [111, 111, 111],
        [121, 121, 121],
        [131, 131, 131],
        [141, 141, 141],
        [151, 151, 151],
        [161, 161, 161],
        [171, 171, 171],
        [181, 181, 181],
        [191, 191, 191]]) 
 torch.Size([20, 3])
Dimension out of range (expected to be in range of [-2, 1], but got 2)
